language: php
dist: xenial

php:
  - 7.2

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

branches:
  only:
    - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - DRUPAL_TRAVIS_TEST_JAVASCRIPT=false

before_install:
  - composer global require thunder/travis
  - test-drupal-module build
  - 'cd /tmp/test/scheduler_content_moderation_integration/install/web/modules/contrib/scheduler; curl "https://www.drupal.org/files/issues/2019-01-23/2798689-170-alternative-approach.patch" | patch -p1'
script:
  - test-drupal-module
